# rQog

*Search, extract and format data from the Quality of Government Institute data*

Quotation form [ Quality of Governance institute website](http://www.qog.pol.gu.se/)

>The QoG Institute was founded in 2004 by Professor Bo Rothstein and Professor Sören Holmberg. It is an independent research institute within the Department of Political Science at the University of Gothenburg. We conduct and promote research on the causes, consequences and nature of Good Governance and the Quality of Government (QoG) - that is, trustworthy, reliable, impartial, uncorrupted and competent government institutions.

>The main objective of our research is to address the theoretical and empirical problem of how political institutions of high quality can be created and maintained. A second objective is to study the effects of Quality of Government on a number of policy areas, such as health, the environment, social policy, and poverty. We approach these problems from a variety of different theoretical and methodological angles.

**Quality of Government institute** provides data in five different data sets

| Dataset description | Data download .csv| Time-series .csv download | Codebook |
| ------------------- | ----------------------------- | ------------------------- | -------- |
| [QoG Basic Data](http://www.qog.pol.gu.se/data/datadownloads/qogbasicdata/) | [cross-sectional](http://www.qogdata.pol.gu.se/data/qog_bas_cs_30aug13.csv) | [time-series](http://www.qogdata.pol.gu.se/data/qog_bas_ts_30aug13.csv) | [codebook](http://www.qogdata.pol.gu.se/codebook/codebook_basic_30aug13.pdf) |
| [QoG Standard Data](http://www.qog.pol.gu.se/data/datadownloads/qogstandarddata/) | [cross-sectional](http://www.qogdata.pol.gu.se/data/qog_std_cs_15may13.csv) | [time-series](http://www.qogdata.pol.gu.se/data/qog_std_ts_15may13.csv) | [codebook](http://www.qogdata.pol.gu.se/codebook/codebook_standard_15may13.pdf) |
| [QoG Social Policy Data](http://www.qog.pol.gu.se/data/datadownloads/qogsocialpolicydata/) | [cross-sectional](http://www.qogdata.pol.gu.se/data/qog_soc_cs_4apr12.csv) | [time-series](http://www.qogdata.pol.gu.se/data/qog_soc_tsl_4apr12.csv) | [codebook](http://www.qogdata.pol.gu.se/codebook/codebook_social_4apr12.pdf) |


| [QoG Expert Survey Data](http://www.qog.pol.gu.se/data/datadownloads/qogexpertsurveydata/) | [individual level](http://www.qogdata.pol.gu.se/data/qog_es_ind_3sep12.csv) | [country level](http://www.qogdata.pol.gu.se/data/qog_es_agg_6sep12.csv) | [codebook](http://www.qogdata.pol.gu.se/codebook/codebook_expert_31aug12.pdf) |
| [QoG EU Regional Data](http://www.qog.pol.gu.se/data/datadownloads/qogeuregionaldata/) | [cross-sectional]() | [time-series]() | [codebook]() |


Christoph Thewes, from University of Potsdam has already provided [user interface for STATA users](http://www.qog.pol.gu.se/data/dataextras/forstatausers/)



**rQog** provides access to 


rustfare utilises the **QoG Standard Data**. Site with more information and code books: [QoG Standard Data](http://www.qog.pol.gu.se/data/datadownloads/qogstandarddata/)


rustfare can be now found under [rOpenGov](https://github.com/rOpenGov/)  in GitHub

## Links

- **Documentation**: [markuskainu.fi/rustfare](http://markuskainu.fi/rqog)
- **Github**: [github.com/muuankarski/rustfare](https://github.com/muuankarski/rQog)




## To install

```{r, eval=FALSE, message=FALSE}
library(devtools)
install_github(repo = "rQog", username = "muuankarski")
library(rQog)
```